name: Push-to-EC2

# Trigger deployment only on push to development branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        
      - name: multiple command
        uses: appleboy/ssh-action@main
        env:
            BRANCH: ${{ github.ref_name }}
            BUILD_NUMBER: ${{ github.run_number }}
 
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          envs: BRANCH, BUILD_NUMBER
          script: |
            pwd
            cd django-notes-app/
            ls
            sudo docker build -t my-app:$BUILD_NUMBER .
            sudo docker stop django-notes-app || true
            sudo docker rm django-notes-app || true
            sudo docker run -d --name django-notes-app -p 8000:8000 my-app:$BUILD_NUMBER
            sudo docker system prune -a -f
